In [161]:
from keras.models import Sequential 
from keras.layers import Dense 
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
import numpy as np 
import tensorflow as tf

In [162]:
# Load Iris dataset 
iris = load_iris() 
X, y = iris.data, iris.target 
 
# Split the dataset into training and testing sets 
X_train, X_test, y_train, y_test = train_test_split(X, y, 
test_size=0.2, random_state=42) 
 
# Standardize features 
scaler = StandardScaler() 
X_train = scaler.fit_transform(X_train) 
X_test = scaler.transform(X_test)

In [163]:
# Encoding y 
print("Before label conversion to categorical: ", y_train[0:5]) # The format of the labels before conversion 
y_train  = tf.keras.utils.to_categorical(y_train, num_classes=3) 
print("After label conversion to categorical: ", y_train[0:5]) # The format of the labels after conversion 
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3) 
 
print("Shape of y_train",y_train.shape) 
print("Shape of y_test",y_test.shape) 

Before label conversion to categorical:  [0 0 1 0 0]
After label conversion to categorical:  [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Shape of y_train (120, 3)
Shape of y_test (30, 3)


In [164]:
#Building Model 
model = Sequential() 
 
# Input layer and first hidden layer 
model.add(Dense(8, activation='relu', input_dim=4)) 
 
# Second hidden layer 
model.add(Dense(8, activation='relu'))

# third hidden layer
#model.add(Dense(4, activation='relu')) 
 
# Output layer 
model.add(Dense(3, activation='softmax'))

c:\Users\hussa\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [165]:
# compiling model 
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [166]:
# training model 
model.fit(X_train, y_train, epochs=50, batch_size=32, 
validation_data=(X_test, y_test))

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0975 - loss: 1.2476 - val_accuracy: 0.0667 - val_loss: 1.2505
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1298 - loss: 1.2237 - val_accuracy: 0.1333 - val_loss: 1.2252
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1965 - loss: 1.1932 - val_accuracy: 0.1667 - val_loss: 1.1995
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2037 - loss: 1.1807 - val_accuracy: 0.1667 - val_loss: 1.1757
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2775 - loss: 1.1430 - val_accuracy: 0.2000 - val_loss: 1.1525
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2754 - loss: 1.1372 - val_accuracy: 0.2333 - val_loss: 1.1308
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3704 - loss: 1.1190 - val_accuracy: 0.3000 - val_loss: 1.1107
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3660 - loss: 1.0994 - val_accuracy: 0.3333 - val_loss: 1.0913
E

In [167]:
# Evluating model 
prediction=model.predict(X_test) 
length=len(prediction) 
y_label=np.argmax(y_test,axis=1) 
predict_label=np.argmax(prediction,axis=1) 
 
accuracy=np.sum(y_label==predict_label)/length * 100  
print("Accuracy of the dataset",accuracy )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Accuracy of the dataset 83.33333333333334
